services:
  - type: web
    name: jee-study-hub
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: RECAPTCHA_SECRET_KEY
       value: 6Lf2Lq8sAAAAAAZbUw84Xuu4JF_wiLFkfo9Kn_Dw
    disk:
      name: db-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 1
